[build]
  base = "."
  command = "npm run build"
  publish = "build"
  
[dev]
  command = "npm run start"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects for Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 